### ISSUE TITLE
docker-compose.yaml中的typecho:php7.3-fpm不存在镜像

### ISSUE THREAD

**Issue by dfaofeng** [Nedved-liao/Dockerfile#2]
请更新下文件......感觉配置起来很麻烦的..

**Comment by Nedved-liao** [comment]
你好，抱歉现在才看到。镜像可以用nedvedliao/typecho:nginx-php7.3-fpm 或者 
registry.cn-hangzhou.aliyuncs.com/docker_typecho/typecho:nginx-php7.3-fpm

**Comment by leonisir** [comment]
> 请更新下文件......感觉配置起来很麻烦的..

你好，抱歉现在才看到。镜像可以用nedvedliao/typecho:nginx-php7.3-fpm 或者
registry.cn-hangzhou.aliyuncs.com/docker_typecho/typecho:nginx-php7.3-fpm
